config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
      @friend = current_user.friends.find_by(id: params[:id])
      redirect_to friends_url, notice: "Not authorized to edit this friend" if @friend.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :phone, :birth ,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="mb-3">
    <% form.label :name, style: "display: block" %>
    <%= form.text_field :name , class: "form-control" , placeholder: "Name"%>
  </div>

  <div class="mb-3">
    <% form.label :email, style: "display: block" %>
    <%= form.text_field :email , class: "form-control" , placeholder: "E-mail" %>
  </div>

  <div class="mb-3">
    <% form.label :phone, style: "display: block" %>
    <%= form.text_field :phone , class: "form-control" , placeholder: "Phone" %>
  </div>

  <div class="mb-3">
    <%= form.label :birth, style: "display: block" %>
    <%= form.date_field :birth %>
  </div>
  <div class="mb-3">
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id ,id: :friend_user_id, class: "form-control" , value: current_user.id, type: :hidden %>
  </div>
  



  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Name:</strong>
    <%= friend.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Birth:</strong>
    <%= friend.birth %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Edit friend</h1>

<%= render "form", friend: @friend %>

<br>


<div>
  <%= link_to "Show", @friend, class:"btn btn-secondary" %> 
  <%= link_to "Delete", @friend, method: :delete , class:"btn btn-danger" %>
  <%= link_to "Back", friends_path, class: "btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <table class="table table-striped  table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>E-mail</th>
        <th></th>
      </tr>
    </thead >
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td><%= link_to friend.name, friend, :style=> 'text-decoration:none;'%></td>
            <td><%= friend.email %></td>
            <td><%= button_to "Delete", friend, method: :delete , class:"btn btn-outline-danger btn-sm" %></td>   
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to "New friend", new_friend_path , class: "btn btn-secondary" %>

<% else %>

  <h1>No Friends</h1>
  <p>just log In and start making your friends list.</p>

<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path , class: "btn btn-dark" %>
</div>

app/views/friends/show.html.erb
    <div class="p-5 mb-4 bg-light rounded-3">
     <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"><%= @friend.name %></h1>
        <div >
         
          <p>
          <strong>E-mail:</strong>
          <%= @friend.email %>
          </p>

          <p>
          <strong>Phone:</strong>
          <%= @friend.phone %>
          </p>

          <p>
          <strong>Date of birth:</strong>
          <%= @friend.birth %>
          </p>

        </div>
        <br>
        <div>
           <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %> 
           <%= link_to "Destroy", @friend, method: :delete, class: "btn btn-danger" %>
           <%= link_to "Back", friends_path, class: "btn btn-dark" %>
        </div>
    </div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" class="navbar bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" href="#">OnLibrary</a> -->
    <%= link_to "Home" , root_path , class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "MyFriends", friends_path, class: "nav-link" %>
        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "Add Friend",  new_friend_path,class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Out",  destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %> 
          <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
         
       
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>  
      <br>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>